# -*- coding: utf-8 -*-
"""myApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LB8iUySmCEPGocucDR4SqTq75VEvmr-C
"""

# pip install streamlit

# pip install yfinance

import yfinance as yf
import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from streamlit_option_menu import option_menu


st.set_page_config(layout='wide')
# Header of the web 
st.title("Stock Market Overview")
st.write("""
    ## Welcome, Thilakna!

   Here is an overview of your stocks!
    """
)

@st.cache_data
def load_data(path: str):
    data = pd.read_csv(path)
    return data




# Select the security

tickerSymbol = st.selectbox('Watch ',['AAPL','TSLA'])
st.sidebar.header("Hello")


tickerData = yf.Ticker(tickerSymbol)

tickerDf = tickerData.history(period='id', start='2010-5-31', end='2020-5-31')


# rand=np.random.normal(1, 2, size=20)
# fig, ax = plt.subplots()
# ax.hist(rand, bins=15)
# st.pyplot(fig)





st.line_chart(tickerDf.Close)
st.line_chart(tickerDf.Volume)

